spring.application.name=cantinhonacional

# Configuração do Banco Local
spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.database=cantinhonacional

# chave secreta
api.security.token.secret=fS6K+9vRzL5W2pX8qN1mZ0jBvE4tA7uC3iO6hG9sYw0=