export const imagensLocais: { [key: string]: any } = {
  "a escrava isaura": require('../../assets/livro/aescravaisaura.jpg'),
  "a estrela sobe": require('../../assets/livro/aestrelasobe.jpg'),
  "a hora da estrela": require('../../assets/livro/ahoradaestrela.jpg'),
  "a mao e a luva": require('../../assets/livro/amaoealuva.jpg'),
  "a vida como ela e": require('../../assets/livro/avidacomoelae.jpg'),
  "angustia": require('../../assets/livro/angustia.jpg'),
  "angústia": require('../../assets/livro/angustia.jpg'),
  
  "bras bexiga e barra funda": require('../../assets/livro/brasbexigaebarrafunda.jpg'),
  "bras, bexiga e barra funda": require('../../assets/livro/brasbexigaebarrafunda.jpg'),
  "brás bexiga e barra funda": require('../../assets/livro/brasbexigaebarrafunda.jpg'),
  "brás, bexiga e barra funda": require('../../assets/livro/brasbexigaebarrafunda.jpg'),
  "Brás bexiga e barra funda": require('../../assets/livro/brasbexigaebarrafunda.jpg'),
  "Bras, bexiga e barra funda": require('../../assets/livro/brasbexigaebarrafunda.jpg'),
  "Brás, bexiga e barra funda": require('../../assets/livro/brasbexigaebarrafunda.jpg'),
  "brasbexigaebarrafunda.jpg": require('../../assets/livro/brasbexigaebarrafunda.jpg'),

  "broqueis": require('../../assets/livro/broqueis.jpg'),
  "casa grande e senzala": require('../../assets/livro/casagrandeesenzala.jpg'),
  "claro enigma": require('../../assets/livro/claroenigma.jpg'),
  "corpo de baile": require('../../assets/livro/corpodebaile.jpg'),
  "dom casmurro": require('../../assets/livro/domcasmurro.jpg'),
  "dona flor e seus dois maridos": require('../../assets/livro/donafloreseusdoismaridos.jpg'),
  "espumas flutuantes": require('../../assets/livro/espumasflutuantes.jpg'),
  "eu": require('../../assets/livro/eu.jpg'),
  "fogo morto": require('../../assets/livro/fogomorto.jpg'),
  "gabriela cravo e canela": require('../../assets/livro/gabrielacravoecanela.jpg'),
  "gabriela, cravo e canela": require('../../assets/livro/gabrielacravoecanela.jpg'),
  "grande sertao veredas": require('../../assets/livro/grandesertaodevaredas.jpg'),
  "grande sertão: veredas": require('../../assets/livro/grandesertaodevaredas.jpg'),
  "grande sertao de varedas": require('../../assets/livro/grandesertaodevaredas.jpg'), 
  "invencao de orfeu": require('../../assets/livro/invencaodeorfeu.jpg'),
  "iracema": require('../../assets/livro/iracema.jpg'),
  "jubiaba": require('../../assets/livro/jubiaba.jpg'),
  "lacos de familia": require('../../assets/livro/lacosdefamilia.jpg'),
  "laços de família": require('../../assets/livro/lacosdefamilia.jpg'),
  "libertinagem": require('../../assets/livro/libertinagem.jpg'),
  "luciola": require('../../assets/livro/luciola.jpg'),
  "macunaima": require('../../assets/livro/macunaima.jpg'),
  "memorial de aires": require('../../assets/livro/memorialdeaires.jpg'),
  "memorias do carcere": require('../../assets/livro/memoriasdocarcere.jpg'),
  "memórias do cárcere": require('../../assets/livro/memoriasdocarcere.jpg'),
  "memorias de bras cubas": require('../../assets/livro/memoriasdebrascubas.jpg'),
  "memorias postumas de bras cubas": require('../../assets/livro/memoriasdebrascubas.jpg'),
  "memórias póstumas de brás cubas": require('../../assets/livro/memoriasdebrascubas.jpg'),
  "memorias sgto de milicias": require('../../assets/livro/memoriadeumsargentodemilicias.jpg'),
  "memórias sgto de milícias": require('../../assets/livro/memoriadeumsargentodemilicias.jpg'),
  "morte e vida severina": require('../../assets/livro/morteevidaseverina.jpg'),
  "o ateneu": require('../../assets/livro/oateneu.jpg'),
  "o cortico": require('../../assets/livro/ocortiço.jpg'),
  "o cortiço": require('../../assets/livro/ocortiço.jpg'),
  "o guarani": require('../../assets/livro/oguarani.jpg'),
  "o quinze": require('../../assets/livro/oquinze.jpg'),
  "o sítio do pica-pau amarelo": require('../../assets/livro/sitiodopicapauamarelo.jpg'),
  "o sitio do pica pau amarelo": require('../../assets/livro/sitiodopicapauamarelo.jpg'),
  "o tempo e o vento": require('../../assets/livro/otempoeovento.jpg'),
  "o uraguai": require('../../assets/livro/ouruguai.jpg'),
  "opera dos mortos": require('../../assets/livro/operadosmortos.jpg'),
  "ópera dos mortos": require('../../assets/livro/operadosmortos.jpg'),
  "os cavalinhos de platiplanto": require('../../assets/livro/oscavalinhosdeplatiplanto.jpg'),
  "os ratos": require('../../assets/livro/osratos.jpg'),
  "os sertoes": require('../../assets/livro/ossertoes.jpg'),
  "os sertões": require('../../assets/livro/ossertoes.jpg'),
  "quincas borba": require('../../assets/livro/quincasborba.jpg'),
  "raizes do brasil": require('../../assets/livro/raizesdobrasil.jpg'),
  "raízes do brasil": require('../../assets/livro/raizesdobrasil.jpg'),
  "romanceiro da inconfidencia": require('../../assets/livro/romanceirodainconfidencia.jpg'),
  "sagarana": require('../../assets/livro/sagarana.jpg'),
  "sao bernardo": require('../../assets/livro/saobernardo.jpg'),
  "são bernardo": require('../../assets/livro/saobernardo.jpg'),
  "sermoes": require('../../assets/livro/sermoes.jpg'),
  "sermões": require('../../assets/livro/sermoes.jpg'),
  "tenda dos milagres": require('../../assets/livro/tendadosmilagres.jpg'),
  "triste fim de policarpo quaresma": require('../../assets/livro/tristefimdepolicarpoquaresma.jpg'),
  "vidas secas": require('../../assets/livro/vidassecas.jpg'),
};

export const imagensHome: { [key: string]: any } = {
  "dom casmurro": require('../../assets/livro/domcasmurro.jpg'),
  "quincas borba": require('../../assets/livro/quincasborba.jpg'),
  
  "grande sertao de varedas": require('../../assets/livro/grandesertaodevaredas.jpg'),
  "grande sertao: veredas": require('../../assets/livro/grandesertaodevaredas.jpg'),
  "grande sertão: veredas": require('../../assets/livro/grandesertaodevaredas.jpg'),
  "grandesertaodevaredas.jpg": require('../../assets/livro/grandesertaodevaredas.jpg'),
  
  "memorias de bras cubas": require('../../assets/livro/memoriasdebrascubas.jpg'),
  "memorias postumas de bras cubas": require('../../assets/livro/memoriasdebrascubas.jpg'),
  "memórias póstumas de brás cubas": require('../../assets/livro/memoriasdebrascubas.jpg'),
  "memoriasdebrascubas.jpg": require('../../assets/livro/memoriasdebrascubas.jpg')
};